name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test
        run: |
          cargo test
          wasm-pack test --chrome --headless

  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm
        run: |
          wasm-pack build --release

      - name: Install node modules
        run: |
          cd www
          npm i

      - name: Build project
        run: |
          cd www
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www/dist
