name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Install wasm pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Test
        run: |
          cargo test
          wasm-pack test --chrome --headless

  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          cd www
          npm run deploy
